# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fromid', models.CharField(max_length=10)),
                ('toid', models.CharField(max_length=10)),
                ('conversation_id', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=256)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
