# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QaPlat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user_id', models.CharField(max_length=10)),
                ('create_date', models.DateField(auto_now=True)),
                ('entity_id', models.CharField(max_length=10)),
                ('entity_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('user_id', models.CharField(max_length=10)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
