# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QaPlat', '0002_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='entity_type',
            field=models.CharField(max_length=1),
        ),
    ]
