# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QaPlat', '0003_auto_20170713_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
