# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltp_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('request_name', models.CharField(max_length=100)),
                ('request_time', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('p', '\u901a\u8fc7'), ('r', '\u62d2\u7edd'), ('w', '\u7b49\u5f85')], max_length=4)),
            ],
        ),
    ]
