# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltp_admin', '0004_remove_classinfo_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
