# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltp_admin', '0005_classinfo_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 29, 11, 7, 2, 389677)),
        ),
    ]
