# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltp_admin', '0006_auto_20170629_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='request_time',
            field=models.DateField(auto_now=True),
        ),
    ]
