# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltp_admin', '0007_auto_20170629_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='status',
            field=models.CharField(default='\u7b49\u5f85', editable=False, max_length=4),
        ),
    ]
