# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltp_admin', '0008_auto_20170629_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='teacher_id',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
